name: Bug Report
description: Create a report to help us improve
labels: [bug]
body:


  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: |
        Carefully read and work through this check list in order to prevent the most common mistakes and misuse of Seal/Yt-dlp:
      options:
        - label: I'm reporting a bug unrelated to a specific site.
          required: true
        - label: I've verified that I'm running the [**latest version**](https://github.com/yt-dlp/yt-dlp/releases/latest) of yt-dlp.
          required: true
        - label: I've verified that I'm running the latest [**stable version**](https://github.com/JunkFood02/Seal/releases/latest/) of Seal or any later [**preview versions**](https://github.com/JunkFood02/Seal/releases).
          required: true
        - label: I've read the [**Contributing guidelines**](https://github.com/JunkFood02/Seal/blob/main/CONTRIBUTING.md) and [**Code Of Conduct.**](https://github.com/JunkFood02/Seal/blob/main/CODE_OF_CONDUCT.md)
          required: true
        - label: I've checkd that the site i'm trying to download from is in the [**Supported Sites**](https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md) list from yt-dlp
          required: true
        - label: I understand that the issue will be (ignored/closed) if I intentionally remove or skip any mandatory field.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description:
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: false

  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: |
        Steps to reproduce the behavior:
        1.Go to '...'
        2.Click on '....'
        3.Scroll down to '....'
        4.See error
    validations:
      required: false

  - type: textarea
    attributes:
      label: Error reports
      placeholder: |
        Click on the displayed error report to copy it.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Screenshots & Screen Records
      placeholder: |
        Screenshots & Screen Records can amp up bug reports.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Device info
      description: |
        Please provide some information of the device you are using.
        You can get the device info by doing these steps:
        1) Open Seal
        2) Go to settings
        3) Click on About
        4) Click "Version"
        5) Paste the info below.
      placeholder: |
        App version: x.x.x (XxXxX)
        Device information: Android XX (API XX)
        Supported ABIs: [arm64-v8a, armeabi-v7a, armeabi]
        Yt-dlp version: 20XX.XX.XX
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description:
      placeholder: |
        Add any other context about the problem here.      
