name: Bug Report
description: Create a report to help us improve
title: "[Bug Report]"
labels: [Bug Report]
body:



  - type: textarea
    attributes:
      label: Describe the bug
      description:
      placeholder: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reproduction Steps
      placeholder: |
        What you did to make it happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Result
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Result
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Device Information
      description: |
        Please provide some information of the device you are using.
        You can get the device info by doing these steps:
        1) Open Seal
        2) Go to settings
        3) Click on About
        4) Long press "Version X.X.X"
      placeholder: |
        Seal Version: X.X.X
        Brand: Samsung
        Architecture: aarch64
        Android Version: 12
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I have searched the open AND closed issues for any duplicates.
          required: true

  - type: textarea
    attributes:
      label: Additional Information
      description: If there is anything else to say, please do so here.

