---
name: "How to do ...❔"
description: "How do I do X or Y with the Devilbox?"
title: "[Howto]: "
labels: ["question", "Community help wanted"]
assignees: []
  
  
  body:
  - type: markdown
    attributes:
      value: |
        If this is a generic question, please consider using the  instead.

  - type: checkboxes
    attributes:
      label: Have you already checked elsewhere?
      description: You may select more than one.
      options:      
        - label: I have read the [Yt-dlp documentation](https://github.com/yt-dlp/yt-dlp#usage-and-options)
        - lable: I'm asking a question and not reporting a bug or requesting a feature
        - label: I have checked [existing issues](https://github.com/JunkFood02/Seal/issues)
        - label: I have googled already with no luck
        - label: I have not done any of the above
    validations:
      required: true

  - type: textarea
    attributes:
      label: What are you struggling with?
      description: Tell the community, what you are struggling with. Be as specific as possible to make it easier for other people to answer your question.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What have you tried already?
      description: Add some details on what you have tried already, so this can be ruled out.
    validations:
      required: true

  - type: textarea
    attributes:
      label: What is your goal?
      description: Tell the community, what you want to accomplish? This might be helpful to know in order to prevent [XY problems](https://en.wikipedia.org/wiki/XY_problem).
    validations:
      required: true
