package com.junkfood.seal.ui.page.settings.network

import android.annotation.SuppressLint
import android.util.Log
import android.webkit.CookieManager
import android.webkit.WebView
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.padding
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Close
import androidx.compose.material3.CenterAlignedTopAppBar
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import com.google.accompanist.web.AccompanistWebChromeClient
import com.google.accompanist.web.AccompanistWebViewClient
import com.google.accompanist.web.WebView
import com.google.accompanist.web.rememberWebViewState
import com.junkfood.seal.R
import com.junkfood.seal.ui.component.connectWithDelimiter
import com.junkfood.seal.util.PreferenceUtil
import com.junkfood.seal.util.PreferenceUtil.COOKIES_DOMAIN

private const val TAG = "WebViewPage"

data class Cookie(
    val domain: String = "",
    val name: String = "",
    val value: String = "",
    val includeSubdomains: Boolean = true,
    val path: String = "/",
    val secure: Boolean = true,
    val expiry: Long = 0L,
) {
    constructor(
        url: String,
        name: String,
        value: String
    ) : this(domain = url.toDomain(), name = name, value = value)

}

fun Cookie.toNetscapeCookieString(): String {
    return connectWithDelimiter(
        domain,
        includeSubdomains.toString().uppercase(),
        path,
        secure.toString().uppercase(),
        expiry.toString(),
        name,
        value,
        delimiter = "\u0009"
    )
}

private fun String.toDomain(): String {
    val regex = Regex("http(s)?://(www|m)?|/.*")
    return this.replace(regex, "")
}

private fun makeCookie(url: String, cookieString: String): Cookie {
    cookieString.split("=").run {
        return Cookie(url = url, name = first(), value = last())
    }
}

@SuppressLint("SetJavaScriptEnabled")
@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun WebViewPage(onDismissRequest: () -> Unit) {
    val cookieManager = CookieManager.getInstance()
    val cookieSet = mutableSetOf<Cookie>()
    val state = rememberWebViewState(PreferenceUtil.getString(COOKIES_DOMAIN, ""))

    Scaffold(modifier = Modifier.fillMaxSize(), topBar = {
        CenterAlignedTopAppBar(title = {}, navigationIcon = {
            IconButton(
                onClick = { onDismissRequest() }) {
                Icon(
                    imageVector = Icons.Outlined.Close,
                    stringResource(id = R.string.close)
                )
            }
        }, actions = {
            TextButton(onClick = {
                val builder =
                    StringBuilder(
                        "# Netscape HTTP Cookie File\n" +
                                "# Auto-generated by Seal built-in WebView\n"
                    )
                cookieSet.forEach {
                    builder.append("\n").append(it.toNetscapeCookieString())
                }
                PreferenceUtil.updateString(
                    PreferenceUtil.COOKIES_FILE,
                    builder.toString()
                )
                onDismissRequest()
            }) {
                Text(stringResource(androidx.appcompat.R.string.abc_action_mode_done))
            }
        })
    }) { paddingValues ->
        val webViewClient = remember {
            object : AccompanistWebViewClient() {
                override fun onPageFinished(view: WebView?, url: String?) {
                    super.onPageFinished(view, url)
                    if (url.isNullOrEmpty()) return
                    cookieManager.getCookie(url)?.let { cookies ->
                        cookies.split("; ").forEach { cookieString ->
                            cookieSet.add(makeCookie(url, cookieString))
                        }
                    }
                    Log.d(TAG, "onPageFinished: $url")
                }
            }
        }
        val webViewChromeClient = remember {
            object : AccompanistWebChromeClient() {
            }
        }
        WebView(
            state = state, client = webViewClient, chromeClient = webViewChromeClient,
            modifier = Modifier
                .padding(paddingValues)
                .fillMaxSize(),
            captureBackPresses = true, factory = { context ->
                WebView(context).apply {
                    settings.javaScriptEnabled = true
                    cookieManager.setAcceptThirdPartyCookies(this, true)
                }
            }
        )


    }
}